<?php

/**
 * This Class represents SendForgotPasswordMail Event which fires on external call
 * @author  Mayank Jariwala <menickwa@gmail.com>
 * @package  App\Events
 * @version  v.1.1
 */

namespace App\Events;

use App\Model\User;
use Illuminate\Broadcasting\Channel;
use Illuminate\Queue\SerializesModels;
use Illuminate\Broadcasting\PrivateChannel;
use Illuminate\Broadcasting\PresenceChannel;
use Illuminate\Foundation\Events\Dispatchable;
use Illuminate\Broadcasting\InteractsWithSockets;
use Illuminate\Contracts\Broadcasting\ShouldBroadcast;

/**
 * Class SendForgotPasswordMail
 *
 * This event is fire when any user forgot password of an application and enter registered
 * email address which help user to receive an system generated mail on his account
 */
class SendForgotPasswordMail
{
    use Dispatchable, InteractsWithSockets, SerializesModels;

    /**
     * @var User: UserObject
     * @var  String: NewPassword Generated by Application
     */
    public $user, $newPassword;

    /**
     * Create a new event instance.
     *
     * @param User $user : User Object
     * @param String $newPassword : New Password of User
     */
    public function __construct(User $user, String $newPassword)
    {
        $this->user = $user;
        $this->newPassword = $newPassword;
    }

    /**
     * Get the channels the event should broadcast on.
     *
     * @return \Illuminate\Broadcasting\Channel|array
     */
    public function broadcastOn()
    {
        return new PrivateChannel('channel-name');
    }
}
